package com.avoverseas.backend.meeting;

public enum MeetingType {
    REQUIREMENT,
    EXPLANATION,
    REQUIREMENT_DISCUSSION,
    ACADEMIC_COUNSELING,
    TUTORING_SESSION,
    MOCK_INTERVIEW,
    UNIVERSITY_SELECTION,
    APPLICATION_GUIDANCE,
    FOLLOW_UP_MEETING
}
